In [1]:
import pandas as pd
import numpy as np

In [10]:

import chardet

with open("PivotTable/gdp.csv", "rb") as f:
    result = chardet.detect(f.read(100000))  # read first 100 KB
print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [13]:
df_gdp = pd.read_csv('PivotTable/gdp.csv',encoding='ISO-8859-1')

In [14]:
df_gdp.head()

   unid wbid      country  year        SES      gdppc  yrseduc  popshare
0     4  AFG  Afghanistan  1970   3.474212  709.00000      NaN  0.003097
1     4  AFG  Afghanistan  1920  26.968016  731.75677      NaN  0.003245
2     4  AFG  Afghanistan  1990   1.269530  604.00000      NaN  0.002347
3     4  AFG  Afghanistan  1960  15.763076  739.00000      NaN  0.003039
4     4  AFG  Afghanistan  2000   2.061114  565.00000      NaN  0.003309

In [17]:
#reshape dataframe with pivot()
pivoted_gdp = df_gdp.pivot(index='year',columns='country',values='gdppc')

In [25]:
pivoted_gdp.round(1)

country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Bahrain,Bangladesh,...,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
year,,,,,,,,,,,,,,,,,,,,,
1880,585.5,522.0,819.2,533.7,1731.5,1041.0,4285.0,2079.0,811.8,566.7,...,1041.0,811.8,3477.0,3184.0,2082.0,653.0,556.6,811.8,533.7,533.7
1890,635.9,598.0,923.4,567.3,2152.0,1139.0,4458.0,2443.0,881.5,587.3,...,1139.0,881.5,4009.0,3392.0,2147.0,737.0,608.3,881.5,567.3,567.3
1900,686.4,685.0,1027.6,601.0,2756.0,1237.0,4013.0,2882.0,951.3,608.0,...,1237.0,951.3,4492.0,4091.0,2219.0,821.0,659.9,951.3,601.0,601.0
1910,736.9,780.0,1131.7,628.7,3822.0,1430.1,5210.0,3290.0,1021.1,661.8,...,1430.1,1021.1,4611.0,4964.0,3136.0,886.0,711.5,1021.1,628.7,628.7
1920,731.8,861.3,1201.2,682.6,3473.0,1432.9,4766.0,2412.0,1242.9,651.9,...,1432.9,3833.7,4548.0,5552.0,2674.0,1173.0,713.9,1017.2,682.6,682.6
1930,702.8,929.6,1255.8,747.8,4080.0,1448.0,4708.0,3586.0,1529.9,614.6,...,1448.0,7821.8,5441.0,6213.0,4301.0,3444.0,695.3,981.8,747.8,747.8
1940,673.9,965.3,1310.4,813.0,4161.0,2144.0,6166.0,3959.0,1817.0,577.3,...,2144.0,11809.9,6856.0,7010.0,3661.0,4045.0,676.6,946.4,813.0,813.0
1950,645.0,1001.0,1365.0,1052.0,4987.0,2841.0,7412.0,3706.0,2104.0,540.0,...,2841.0,15798.0,6939.0,9561.0,4659.0,7462.0,658.0,911.0,661.0,701.0
1960,739.0,1451.0,2088.0,1253.0,5559.0,3945.0,8791.0,6519.0,2843.0,545.0,...,3945.0,22433.0,8645.0,11328.0,4960.0,9646.0,799.0,964.0,960.0,938.0
1970,709.0,2004.0,2249.0,1768.0,7302.0,5575.0,12024.0,9747.0,3788.0,630.0,...,5575.0,24552.0,10767.0,15030.0,5184.0,10672.0,735.0,1230.0,1073.0,1282.0
1980,690.0,2347.0,3152.0,961.0,8206.0,6116.6,14412.0,13759.0,4388.0,549.0,...,5378.2,27709.0,12931.0,18577.0,6555.0,10139.0,757.0,2290.0,911.0,1295.0
1990,604.0,4557.4,10238.9,4806.4,10833.5,3735.5,28572.1,31265.3,35112.6,1290.4,...,10464.0,114518.8,26769.4,37062.1,9840.7,14450.7,1501.1,3353.8,2308.6,2526.1
2000,565.0,5470.0,10211.1,3831.0,14924.4,2918.6,35244.5,38812.1,44791.5,1645.7,...,4797.4,107206.5,32961.5,45986.1,12874.8,14417.1,2649.7,3911.2,2092.3,2521.3
2010,1662.8,9927.2,12898.3,6492.2,18794.3,6507.9,41363.2,43175.0,39912.7,2451.3,...,7824.5,57406.7,36195.9,49372.8,17082.4,16563.4,4486.3,4481.6,3263.4,1389.0

In [27]:
#testing
pivoted_gdp.iloc[:,130:].round(1)

country,Tajikistan,Tanzania,Thailand,Togo,Tonga,Trinidad & Tobago,Tunisia,Turkey,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
year,,,,,,,,,,,,,,,,,,,
1880,1041.0,533.7,696.0,533.7,585.5,583.3,691.1,915.2,533.7,1041.0,811.8,3477.0,3184.0,2082.0,653.0,556.6,811.8,533.7,533.7
1890,1139.0,567.3,784.0,567.3,635.9,680.7,749.3,1005.5,567.3,1139.0,881.5,4009.0,3392.0,2147.0,737.0,608.3,881.5,567.3,567.3
1900,1237.0,601.0,808.8,601.0,686.4,778.0,807.4,1095.7,601.0,1237.0,951.3,4492.0,4091.0,2219.0,821.0,659.9,951.3,601.0,601.0
1910,1430.1,628.7,833.6,628.7,736.9,978.0,865.6,1185.9,628.7,1430.1,1021.1,4611.0,4964.0,3136.0,886.0,711.5,1021.1,628.7,628.7
1920,1432.9,682.6,820.0,682.6,871.8,1536.7,926.9,862.3,682.6,1432.9,3833.7,4548.0,5552.0,2674.0,1173.0,713.9,1017.2,682.6,682.6
1930,1448.0,747.8,796.7,747.8,1042.8,2249.1,989.6,1249.0,747.8,1448.0,7821.8,5441.0,6213.0,4301.0,3444.0,695.3,981.8,747.8,747.8
1940,2144.0,813.0,824.5,813.0,1213.9,2961.6,1052.3,1675.0,813.0,2144.0,11809.9,6856.0,7010.0,3661.0,4045.0,676.6,946.4,813.0,813.0
1950,2841.0,424.0,817.0,574.0,1385.0,3674.0,1115.0,1623.0,687.0,2841.0,15798.0,6939.0,9561.0,4659.0,7462.0,658.0,911.0,661.0,701.0
1960,3945.0,459.0,1078.0,698.0,1632.0,6251.0,1343.0,2247.0,713.0,3945.0,22433.0,8645.0,11328.0,4960.0,9646.0,799.0,964.0,960.0,938.0
1970,5575.0,568.0,1694.0,1075.0,2082.0,8244.0,1827.0,3078.0,867.0,5575.0,24552.0,10767.0,15030.0,5184.0,10672.0,735.0,1230.0,1073.0,1282.0
1980,3649.5,601.0,2554.0,1097.0,2522.0,12380.0,2944.0,4022.0,572.0,5378.2,27709.0,12931.0,18577.0,6555.0,10139.0,757.0,2290.0,911.0,1295.0
1990,3635.3,1472.7,6650.7,1350.1,3574.2,12255.4,5614.9,10954.0,783.1,10464.0,114518.8,26769.4,37062.1,9840.7,14450.7,1501.1,3353.8,2308.6,2526.1
2000,1185.6,1489.7,9228.2,1302.0,4610.4,18324.0,7573.9,13357.6,1077.7,4797.4,107206.5,32961.5,45986.1,12874.8,14417.1,2649.7,3911.2,2092.3,2521.3
2010,2123.0,2111.2,13584.2,1229.5,4993.0,31261.0,10437.1,17076.6,1573.5,7824.5,57406.7,36195.9,49372.8,17082.4,16563.4,4486.3,4481.6,3263.4,1389.0

### pivot_table()

In [32]:
df_sales = pd.read_excel('PivotTable/supermarket_sales.xlsx')

In [42]:
df_sales.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3

In [40]:
#make a pivot table and add an aggregate function 
df_sales.pivot_table(index='Gender',aggfunc='mean') #only columns with numerical data are displayed

/var/folders/tg/kszh77s55jx6qvbm3rpmv0l40000gn/T/ipykernel_48526/209326015.py:2: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  df_sales.pivot_table(index='Gender',aggfunc='mean') #only columns with numerical data are displayed

,Quantity,Rating,Tax 5%,Total,Unit price,cogs,gross income,gross margin percentage
Gender,,,,,,,,
Female,5.726547,6.964471,15.956936,335.095659,55.263952,319.138723,15.956936,4.761905
Male,5.292585,6.980962,14.799487,310.789226,56.081944,295.989739,14.799487,4.761905

In [48]:
#make a pivot table, add an aggregate function and select some columns
df_sales.pivot_table(index='Gender',values=['Quantity','Total'],columns='Product line',aggfunc='sum').round(1)

                           Quantity                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Gender
Female                          488                 530                514
Male                            483                 372                438

                                                                     \
Product line Health and beauty Home and lifestyle Sports and travel
Gender
Female                     343                498               496
Male                       511                413               424

                              Total                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Gender
Female                      27102.0             30437.4            33170.9
Male                        27235.5             23868.5            22973.9


Product line Health and beauty Home and lifestyle Sports and travel
Gender
Female                 18561.0            30036.9           28574.7
Male                   30632.8            23825.0           26548.1